version: '3.3'

networks:
  aws-training:

services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    networks:
      - aws-training
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aws_training
      MYSQL_USER: test
      MYSQL_PASSWORD: test